name: Cache test
on:
    workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: instsall node.js
              uses: actions/setup-node@v6.1.0
              with:
                node-version: 20
            - name: Cache node.js dependencies
              id: cache-node
              uses: actions/cache@v3
              with:
                path: |
                  node_modules
                  ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
                restore-keys: ${{ runner.os }}-node-
            - name: install dependencies
              if: steps.cache-node.outputs.cache-hit != 'true'
              run: npm install
            
            - name: unit test
              run: npm run test
            - name: build static files
              run: npm run build             