name: services-container
on:
    workflow_dispatch: 
    push: 

jobs:
    multi-services:
        runs-on: ubuntu-latest
        services:
          nginx:
            image: nginx:alpine
            ports:
              - 80:80
          
          apache:
            image: httpd:2.4
            ports:
              - 8080:80

        steps:
          - name: Check NGINX server
            run: |
              echo "Checking NGINX..."
              curl -f http://nginx
        
          - name: Check Apache server
            run: |
              echo "Checking Apache..."
              curl -f http://apache   

